### ISSUE TITLE
logs are not sent from within uwsgi

### ISSUE THREAD

**Issue by naphtul** [logzio/logzio-python-handler#16]
Scenario:

1. Install uwsgi (example [instructions](https://www.digitalocean.com/community/tutorials/how-to-set-up-uwsgi-and-nginx-to-serve-python-apps-on-ubuntu-14-04))
2. Implement the logz.io python handler to issue a log from within the uwsgi python application you used as an example.
3. Call the uwsgi entry point.

Expected result:
Logs would arrive at logz.io

Actual result:
Logs are written in the console and to a file (if you've set it up like that) but not to logz.io.

Additional information:
I was advised to use filebeat instead, but this won't let me utilize the extra fields capability exposed by issue #14 .

**Comment by itayl2** [comment]
Crucially needed by us as well.

**Comment by roiravhon** [comment]
Hey @naphtul,
Can you please attach the errors you get? or a zip with a sample project we can debug?

**Comment by naphtul** [comment]
1. Unzip [uwsgi_test_logger.zip](https://github.com/logzio/logzio-python-handler/files/1603861/uwsgi_test_logger.zip) into a folder on your linux machine with uwsgi installed.
2. Type `uwsgi --ini test_logger.ini` while in that folder.
3. Go to your browser and go to this machine: http://localhost:8080/py/app7
4. View the console (where you typed the uwsgi command earlier): The message is there.
5. View the uwsgi.log file that was created in that folder: The message is there.
6. Search in logz.io for the message: It is **not** there.

```
[test-user@test-machine ~]$ uwsgi --ini test_logger.ini
[uWSGI] getting INI configuration from test_logger.ini
*** Starting uWSGI 2.0.15 (64bit) on [Thu Jan  4 15:59:02 2018] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 02 January 2018 17:18:52
os: Linux-4.9.70-25.242.amzn1.x86_64 #1 SMP Wed Jan 3 05:36:22 UTC 2018
nodename: test-machine.com
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/test-user
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 15715
your memory page size is 4096 bytes
detected max file descriptor number: 1024
- async cores set to 10 - fd table size: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8080 fd 3
initializing 10 uGreen threads with stack size of 262144 (256 KB)
uwsgi socket 0 bound to UNIX address test_logger.sock fd 6
Python version: 3.5.1 (default, Nov  2 2017, 19:18:26)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
Python main interpreter initialized at 0x783bb0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 993024 bytes (969 KB) for 50 cores
*** Operational MODE: preforking+async ***
mounting test_logger.py on /py/app7
WSGI app 0 (mountpoint='/py/app7') ready in 0 seconds on interpreter 0x783bb0 pid: 9150 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9150)
spawned uWSGI worker 1 (pid: 9157, cores: 10)
spawned uWSGI worker 2 (pid: 9158, cores: 10)
spawned uWSGI worker 3 (pid: 9159, cores: 10)
spawned uWSGI worker 4 (pid: 9160, cores: 10)
spawned uWSGI worker 5 (pid: 9161, cores: 10)
spawned uWSGI http 1 (pid: 9162)
2018-01-04 15:59:28,316 DEBUG test_logger.py application() This is a uwsgi logz.io test
[pid: 9158|app: 0|req: 1/1] 52.135.65.77 () {36 vars in 642 bytes} [Thu Jan  4 15:59:28 2018] GET /py/app7 => generated 42 bytes in 1 msecs (HTTP/1.1 200) 1 headers in 44 bytes (4 switches on core 9)
2018-01-04 15:59:28,663 DEBUG test_logger.py application() This is a uwsgi logz.io test
[pid: 9160|app: 0|req: 1/2] 52.135.65.77 () {36 vars in 614 bytes} [Thu Jan  4 15:59:28 2018] GET /favicon.ico => generated 42 bytes in 1 msecs (HTTP/1.1 200) 1 headers in 44 bytes (4 switches on core 9)
```

**Comment by roiravhon** [comment]
Hey @naphtul, we are still investigating this.
Things are super weird, and really hard to debug.

How is your understanding of uwsgi internal mechanism?

**Comment by naphtul** [comment]
@roiravhon , thanks for your efforts. My understanding varies from bad to really bad.

**Comment by roiravhon** [comment]
Ok. we will invest some more time on that, but it's really hard without understanding uwsgi.
We can see the logs are being added to the queue, but the queue is empty when draining it - although the queues are the same based on their memory address.

We can't find an explanation currently

**Comment by naphtul** [comment]
Maybe this can help?
http://uwsgi-docs.readthedocs.io/en/latest/Logging.html

**Comment by roiravhon** [comment]
We saw that @naphtul.. we're looking for more details about how uwsgi behaves in a multi-threaded, multi-process environment

**Comment by zaitboded** [comment]
Following.
Also unable to see logs

**Comment by jo-tham** [comment]
Possibly related, I'm having the same issue with logging from celery tasks as the celery master process forks into the worker process, which results in the sending thread being unavailable in the worker process. 

@naphtul have you enabled python threads or tried `master=False` with uwsgi?

@roiravhon is this a known issue (logzio handler won't work after `os.fork()`)?

**Comment by roiravhon** [comment]
@jo-tham not a known issue. We saw some really weird behavior under uwsgi, that we can't really explain

**Comment by roiravhon** [comment]
@naphtul can you please check if @jo-tham change fixed your issue as well?
Version 2.0.7

**Comment by naphtul** [comment]
Yes, `master=false` and 2.0.7 works fine.

**Comment by roiravhon** [comment]
Awesome!

**Comment by Silby17** [comment]
I have recently encountered the same problem and I solved it by setting `master=false` as well as `processes =1`
Basically when Logz.io is trying to send the log uWSGI kills the thread. By setting `processes=1` kept one thread and therefore the data was sent.

**Comment by idohalevi** [comment]
@Silby17 
Thank you :)

**Comment by devstarkes** [comment]
What to do if I need `master=true`? For example in flask application.

**Comment by Silby17** [comment]
I ended up using Log shipping with Filebeat

**Comment by zolfariot** [comment]
Hello everyone,
I experienced the issue and I think a got a slightly better understanding of what is going on.
With `master=true` or `process = N` with N>1 uwsgi needs to do some forking.

If `master=true` a master process is started, your python module is loaded, then the master process is forked N times to generate workers that executes the app in your python module.

In the case `master=false` and `process =N` with N>1 something similar should happen to generate all the workers.

The problem arise from the fact that you probably initialize your logging framework somewhere within your module before the actual `app` (flask.Flask, for instance) is instanciated and started.

In this case the LogzioSender instance used by the LogzioHandler is created within the parent (master) process.
When the master process is forked, in *nix systems, all memory objects (including Thread representations) are duplicated (cow), but the actual Thread is destroyed.

Unfortunately the python `Thread()` `is_alive()` in this particular situation seems to keep returning `True`, it checks whether the function in the thread has been stopped or the thread never started, but has no check to verify if the Thread actually still exists.

For this reason the condition implemented in Logz.io `sender.py` (https://github.com/logzio/logzio-python-handler/blob/7a7758d900c8b9d218ebf26361de7df21c0383dd/logzio/sender.py#L70) is not able to catch the fact the Thread has been destroyed and is not initializing a new one.
Actually the Thread is not running but the Queue (this one correctly duplicated at the moment of the fork) is working correctly and getting filled with all the events.

Possibles workarounds to keep using the master process or uwsgi multiple worker processes requires to postpone/repeat the Thread creation after the workers process have been forked.

In my setup I used the `@postfork` decorator from `uwsgidecorators` to reinitialize the LogzioHandler immediately after each f
```python
import logging
from logzio.handler import LogzioHandler

try:
     import uwsgi
     from uwsgidecorators import postfork
except ImportError:
     # if we are outside uwsgi use a mock postfork decorator that just execute the decorated func
     def postfork(func):
          func()
          return func

@postfork
def configure_logging():
     logzio_handler = LogzioHandler(token=, url=, ...)
     logging.basicConfig(level=logging.INFO, handlers=[logzio_handler])
```

This way the problem is partially addressed, one sender worker Thread is initiated for each different process, but two aspects remain unaddressed:

1. The system always think that the MainThread exited, because its expecting a Thread named "MainThread" while in uWSGI main threads use different names. This will cause LogzioSender to terminate prematurely. As a workaround I changed the sender.py code from:
https://github.com/logzio/logzio-python-handler/blob/7a7758d900c8b9d218ebf26361de7df21c0383dd/logzio/sender.py#L51-L52
to:
```python
        self.is_main_thread_active = lambda: any(
            (i.name == 'MainThread' or i.name.startswith('uWSGI')) and i.is_alive() for i in enumerate())
```
2. The last remaining unaddressed problem: if sending fails, backup is written to file. Since now this can happen concurrently (one thread the per process) some file locking must be implemented to avoid corruption or race conditions. Or as an alternative logging can be done in a separate worker Process for all the different Processes, but for this we would need a multiprocessing.Queue instead of a queue.Queue and a lot of rewriting.
