### ISSUE TITLE
Production Release?

### ISSUE THREAD

**Issue by tylfin** [logzio/logzio-python-handler#3]
Hey guys, is there a timeline for the production release of the logzio-python-handler? 

I see that the line `This is in BETA. We currently use this handler internally. We will provide tests soon` is 10 months old, and we'd like to start using this. 

Cheers

**Comment by roiravhon** [comment]
Hey @tylfin!
Well, this is due to lack of complete automated testing in place.
As the line say, we use this internally and have some customers using this as well.
We have some mileage with this handler and provided a couple of versions, PRs and fixes.

But, we can't still say it is 100% GA since the lack of complete automated testing framework. (which unfortunately I still don't have a schedule)

You can go in the in-app chat to support and request that this will get GA through our internal ticketing system.

Thanks,
Roi.

**Comment by roiravhon** [comment]
Hey @tylfin!
Just as a followup - version 2.0, stable, was released last week.

I remembered your ticket, so just wanted to let you know.

**Comment by tylfin** [comment]
@roiravhon Thank you! I also received a direct email -- I appreciate the communications!
